apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: it19127538
  name: it19127538
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: it19127538
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: it19127538
    spec:
      containers:
        # - image: it19062266/ctse_user:latest
        - image: dockerdhananjaya/ctse-assignment3-it19127538:{{tag}}
          imagePullPolicy: Always
          name: ctse-assignment3-it19127538
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 6000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30