apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: it19127538
  name: it19127538
spec:
  ports:
    - port: 6000
      protocol: TCP
      targetPort: 6000
  selector:
    app: it19127538
status:
  loadBalancer: {}